Clean up unused functions / iex load
GamestonkTerminal/GamestonkTerminal pull request #1047
Opened 2021-12-09 22:10 UTC by jmaslek

Address #1042  and #1044 

@Chavithra not sure if this will destroy some tests

- Removes the two unused plot functions
- Redefines the iex loading and eliminates intraday for non yf data

2021-12-10 03:57 UTC, Chavithra requested changes
Apparently it can't find `s_start` variable in a print statement.

Here is the code I have run :
```python
from datetime import datetime
from gamestonk_terminal.stocks import stocks_helper

stock = stocks_helper.load(
    ticker="TSLA",
    start=datetime.strptime("2021-12-05", "%Y-%m-%d"),
    interval=1440,
)
```

Here is the displayed message :
```
local variable 's_start' referenced before assignment
```

2021-12-10 04:15 UTC, Chavithra commented on gamestonk_terminal/stocks/stocks_helper.py
> +    iexrange: str = "tyd",
I think it should be "ytd"

2021-12-10 15:02 UTC, jmaslek commented
> Apparently it can't find `s_start` variable in a print statement.
> 
> Here is the code I have run :
> 
> ```python
> from datetime import datetime
> from gamestonk_terminal.stocks import stocks_helper
> 
> stock = stocks_helper.load(
>     ticker="TSLA",
>     start=datetime.strptime("2021-12-05", "%Y-%m-%d"),
>     interval=1440,
> )
> ```
> 
> Here is the displayed message :
> 
> ```
> local variable 's_start' referenced before assignment
> ```

Fixed.  Had an incorrect tab

2021-12-11 06:12 UTC, Chavithra approved these changes
Seems to work, was able to :
- pass the test with `iex daily`
- get `candle graph` for `iex loaded`data`

2021-12-11 15:07 UTC, DidierRLopes approved these changes

2021-12-11 15:07 UTC, DidierRLopes commented on gamestonk_terminal/stocks/stocks_controller.py
> +            choices=["yf", "av", "iex"] if "-i" not in other_args else ["yf"],
nice one

2021-12-11 15:07 UTC, merged