First working program
GamestonkTerminal/GamestonkTerminal pull request #1123
Opened 2022-01-01 00:58 UTC by colin99d

Changed the reports context into the Jupyter context. I then made sub menus for Reports and Dashboards. The reports is for papermill reports like the ones that already existed. The dashboards are for interactive pages like mine. I also added Voila support. Voila is much better for our non-coder friends, since it presents a much sleeker environment to get data, while leaving the jupyter-lab as default encourages tinkering, and PRS :) . Once this has been reviewed and changes requested are added I will update the documentation.

2022-01-01 17:57 UTC, DidierRLopes requested changes
On top of this:
* the notebook reports should be fixed because of the change of location
* the jupyter/reports controller should be updated to reflect new path + fix reset
* the `test_reports_base.gst` and `test_reports.gst` files need to be updated to reflect this change of location
* merge with main since `dd` notebook report was changed
* `(✨) /dashboard/ $ stocks -h` crashes
* Why not have Voila by default? It looks very nice!

Finally, @piiq has suggested for us to not open a port on the user's machine as this can lead to security issues. Hence why we deprecated such for the reports. I think here we would want to do the same, we can probably ask the user to run jupyter kernel behind the scenes or so... and then the user can say "Y" when he has done that, and we open the jupyter lab. Also, I don't like the fact that after we can enter in one of these, we can't keep using the terminal as "Ctrl+C" will make it crash (unless there's a smooth way to exit that I'm unaware).
<img width="1224" alt="Screenshot 2022-01-01 at 17 50 53" src="https://user-images.githubusercontent.com/25267873/147856942-6d3eb5c7-1f61-4aa9-92f9-e019070d207b.png">
<img width="1100" alt="Screenshot 2022-01-01 at 17 53 54" src="https://user-images.githubusercontent.com/25267873/147856999-15b2a67a-31fe-4253-8ded-0225312d4597.png">

2022-01-01 17:57 UTC, DidierRLopes commented on gamestonk_terminal/jupyter/dashboards/dashboards_controller.py
> +Dashboards:
No need for this

2022-01-01 17:57 UTC, DidierRLopes commented on gamestonk_terminal/jupyter/dashboards/dashboards_controller.py
> +                print(f"{get_flair()} /dashboard/ $ {an_input}")
should be `/jupyter/dashboard/`

2022-01-01 17:57 UTC, DidierRLopes commented on gamestonk_terminal/jupyter/dashboards/dashboards_controller.py
> +                    f"{get_flair()} /dashboard/ $ ",
should be `/jupyter/dashboard/`

2022-01-01 17:57 UTC, DidierRLopes commented on gamestonk_terminal/jupyter/dashboards/dashboards_controller.py
> +                an_input = input(f"{get_flair()} /dashboard/ $ ")
should be `/jupyter/dashboard/`

2022-01-01 17:57 UTC, DidierRLopes commented on gamestonk_terminal/jupyter/jupyter_controller.py
> +        "finra",
You don't want any of those below, only reports and dashboards. And it should be named `CHOICES_MENUS` instead

2022-01-01 17:57 UTC, DidierRLopes commented on gamestonk_terminal/jupyter/jupyter_controller.py
> +Jupyter:
no need for this line

2022-01-01 17:57 UTC, DidierRLopes commented on gamestonk_terminal/jupyter/jupyter_controller.py
> +   reports       creates jupyter reports
This spacing is not the correct one and you are missing the ">" which distinguishes menu from command:
```
>   resources
    
(✨) / $ jupyter

Jupyter:
   reports       creates jupyter reports
   dashboards    shows interactive jupyter dashboards  
```

Should be:
```
>   reports       creates jupyter reports
>   dashboards    shows interactive jupyter dashboards  
```

2022-01-01 17:57 UTC, DidierRLopes commented on gamestonk_terminal/jupyter/jupyter_controller.py
> +        self.queue.insert(0, "resources")
`self.queue.insert(0, "jupyter")`

2022-01-01 17:57 UTC, DidierRLopes commented on terminal.py
>  >   reports
This one should be removed

2022-01-01 17:57 UTC, DidierRLopes commented on terminal.py
>          "reports",
This should be removed

2022-01-01 19:33 UTC, jmaslek commented
I fixed the build issue, so if you merge, the last test should pass.

2022-01-02 15:48 UTC, colin99d commented
> On top of this:
> 
> * the notebook reports should be fixed because of the change of location
> * the jupyter/reports controller should be updated to reflect new path + fix reset
> * the `test_reports_base.gst` and `test_reports.gst` files need to be updated to reflect this change of location
> * merge with main since `dd` notebook report was changed
> * `(✨) /dashboard/ $ stocks -h` crashes
> * Why not have Voila by default? It looks very nice!
> 
> Finally, @piiq has suggested for us to not open a port on the user's machine as this can lead to security issues. Hence why we deprecated such for the reports. I think here we would want to do the same, we can probably ask the user to run jupyter kernel behind the scenes or so... and then the user can say "Y" when he has done that, and we open the jupyter lab. Also, I don't like the fact that after we can enter in one of these, we can't keep using the terminal as "Ctrl+C" will make it crash (unless there's a smooth way to exit that I'm unaware). <img alt="Screenshot 2022-01-01 at 17 50 53" width="1224" src="https://user-images.githubusercontent.com/25267873/147856942-6d3eb5c7-1f61-4aa9-92f9-e019070d207b.png"> <img alt="Screenshot 2022-01-01 at 17 53 54" width="1100" src="https://user-images.githubusercontent.com/25267873/147856999-15b2a67a-31fe-4253-8ded-0225312d4597.png">

Could we have a prompt that explains jupyter-lab and what exactly happens and then prompt them with a y/n on whether they would like to proceed? That way they can understand what is happening while also getting time savings from using the terminal.

2022-01-02 21:58 UTC, DidierRLopes commented
> > On top of this:
> > 
> > * the notebook reports should be fixed because of the change of location
> > * the jupyter/reports controller should be updated to reflect new path + fix reset
> > * the `test_reports_base.gst` and `test_reports.gst` files need to be updated to reflect this change of location
> > * merge with main since `dd` notebook report was changed
> > * `(✨) /dashboard/ $ stocks -h` crashes
> > * Why not have Voila by default? It looks very nice!
> > 
> > Finally, @piiq has suggested for us to not open a port on the user's machine as this can lead to security issues. Hence why we deprecated such for the reports. I think here we would want to do the same, we can probably ask the user to run jupyter kernel behind the scenes or so... and then the user can say "Y" when he has done that, and we open the jupyter lab. Also, I don't like the fact that after we can enter in one of these, we can't keep using the terminal as "Ctrl+C" will make it crash (unless there's a smooth way to exit that I'm unaware). <img alt="Screenshot 2022-01-01 at 17 50 53" width="1224" src="https://user-images.githubusercontent.com/25267873/147856942-6d3eb5c7-1f61-4aa9-92f9-e019070d207b.png"> <img alt="Screenshot 2022-01-01 at 17 53 54" width="1100" src="https://user-images.githubusercontent.com/25267873/147856999-15b2a67a-31fe-4253-8ded-0225312d4597.png">
> 
> Could we have a prompt that explains jupyter-lab and what exactly happens and then prompt them with a y/n on whether they would like to proceed? That way they can understand what is happening while also getting time savings from using the terminal.

I'm fine with that as long as that message states what is gonna happen if they press `yes`

2022-01-03 13:40 UTC, colin99d commented on gamestonk_terminal/jupyter/dashboards/dashboards_controller.py
> +Dashboards:
Which part is unneeded?

2022-01-04 23:15 UTC, DidierRLopes requested changes
<img width="1622" alt="Screenshot 2022-01-04 at 23 12 36" src="https://user-images.githubusercontent.com/25267873/148136470-853cfc4a-18bb-4a31-bce7-fdc64db9dd0d.png">

Still crashing, you just need to create that folder and add a `.gitkeep` file inside. `git` doesn't track folders, therefore you need to "trick" git by adding a meaningful hidden file in there

2022-01-04 23:30 UTC, colin99d commented
> <img alt="Screenshot 2022-01-04 at 23 12 36" width="1622" src="https://user-images.githubusercontent.com/25267873/148136470-853cfc4a-18bb-4a31-bce7-fdc64db9dd0d.png">
> 
> Still crashing, you just need to create that folder and add a `.gitkeep` file inside. `git` doesn't track folders, therefore you need to "trick" git by adding a meaningful hidden file in there

Done! Apologies good sir.

2022-01-05 00:16 UTC, DidierRLopes commented
eheh sorry to nag again, but you have added the wrong path it should be `jupyter/reports/stored`. Also, the name of the file should actually be `.gitkeep` - it's a convention thing AFAIK

2022-01-05 00:43 UTC, DidierRLopes commented
Last one hopefully (😄) the .html opening has not the correct path, it has 2 `gamestonk_terminal` when it should be a single one

2022-01-05 00:47 UTC, DidierRLopes commented
<img width="427" alt="Screenshot 2022-01-05 at 00 47 12" src="https://user-images.githubusercontent.com/25267873/148143256-a184d1a3-e6b4-4001-9593-4f97d6adb2a6.png">

exit is not exiting

2022-01-05 00:49 UTC, colin99d commented
> 

What do you mean by this?

2022-01-05 00:51 UTC, jmaslek commented
> What do you mean by this?

`exit` should leave the terminal.  In `call_exit` , you probably need an extra self.queue.insert(0,"quit")

2022-01-05 00:52 UTC, colin99d commented
> Last one hopefully (😄) the .html opening has not the correct path, it has 2 `gamestonk_terminal` when it should be a single one

Sorry meant this one

2022-01-05 01:00 UTC, DidierRLopes commented
<img width="1622" alt="Screenshot 2022-01-04 at 23 12 36" src="https://user-images.githubusercontent.com/25267873/148136470-853cfc4a-18bb-4a31-bce7-fdc64db9dd0d.png">


> > Last one hopefully (😄) the .html opening has not the correct path, it has 2 `gamestonk_terminal` when it should be a single one
> 
> Sorry meant this one
<img width="1270" alt="Screenshot 2022-01-05 at 00 59 34" src="https://user-images.githubusercontent.com/25267873/148144174-36469a8d-75f0-4fd6-88f5-0e3a68542171.png">

So the exported file is correct, however my browser opened automatically with a different URL with a `gamestonk_terminal/gamestonk_terminal` in the path.

2022-01-05 01:49 UTC, DidierRLopes approved these changes
🦋 🚀  Flyiiinnggggg

2022-01-05 01:51 UTC, merged