Crypto Tool: Calculate potential returns
GamestonkTerminal/GamestonkTerminal pull request #1146
Opened 2022-01-06 15:50 UTC by jose-donato

This PR adds new `prt` command which is tool to calculate potential returns of the coin that is loaded

Examples:
* Compare with another coin: what if `algorand` reaches `bitcoin` market cap (--vs bitcoin)
![image](https://user-images.githubusercontent.com/43375532/148409887-00deaa08-89e2-4f75-963c-8643cfef2e93.png)
* Compare if loaded coin reaches a target price of $5 (--price 5)
![image](https://user-images.githubusercontent.com/43375532/148409938-0010fe31-6a3c-4dde-9404-1696a5468247.png)
* Compare with 5 coins with highest market cap (--top 5)
![image](https://user-images.githubusercontent.com/43375532/148410282-d539990b-c9ef-4761-baca-3a4401bc1a67.png)

2022-01-06 16:38 UTC, jmaslek requested changes
What is the insight this provides?  If doge goes to 1Million dollars , I will have millions of returns, but that doesn't provide any investment insight

2022-01-06 17:18 UTC, jose-donato commented
> What is the insight this provides? If doge goes to 1Million dollars , I will have millions of returns, but that doesn't provide any investment insight

Yea good point. I don't think it provides any investment insight but is a funny tool to share hopium with friends 😄

2022-01-06 17:23 UTC, jmaslek commented
> Yea good point. I don't think it provides any investment insight but is a funny tool to share hopium with friends 😄
> 
> In the future we can add more calculators/tools (e.g., calculate APR and APY returns, mining profitability, ...) and create a menu for them.

Fair point.  Ill allow it ;) ...once the tests pass.

Also -- 61 files changed - did you branch this off of the crypto refactor menu?

2022-01-06 21:40 UTC, jose-donato commented
> > Yea good point. I don't think it provides any investment insight but is a funny tool to share hopium with friends 😄
> 
> > 
> 
> > In the future we can add more calculators/tools (e.g., calculate APR and APY returns, mining profitability, ...) and create a menu for them.
> 
> 
> 
> Fair point.  Ill allow it ;) ...once the tests pass.
> 
> 
> 
> Also -- 61 files changed - did you branch this off of the crypto refactor menu?

Yea...

2022-01-07 11:09 UTC, DidierRLopes commented on gamestonk_terminal/reports/stored/20211102_161336_econ_data.md
> +# Economy Data - 2021/11/02 16:16:06
You shouldn't be committing these files. That's why test is failing.

Since you are at it, can you add this folder to gitignore?

2022-01-07 13:08 UTC, DidierRLopes approved these changes

2022-01-07 13:15 UTC, DidierRLopes commented
@jmaslek blocked by your requested changes still

2022-01-07 14:40 UTC, jmaslek approved these changes

2022-01-07 14:53 UTC, merged