funds + custom
GamestonkTerminal/GamestonkTerminal pull request #1311
Opened 2022-02-04 01:48 UTC by jmaslek

Hit these two easy menus

2022-02-04 23:02 UTC, piiq requested changes
Hey! Thanks! I left comments in the code.

One more question - does this require cleaning out non-trading days?

2022-02-04 23:02 UTC, piiq commented on gamestonk_terminal/mutual_funds/investpy_view.py
> +    ax.yaxis.set_label_position("right")
this is set with other style stuff in `theme.style_primary_axis`, so no need to have it in the view

2022-02-04 23:08 UTC, jmaslek commented
> One more question - does this require cleaning out non-trading days?

It does not.  No intraday

2022-02-08 14:11 UTC, piiq approved these changes

2022-02-08 14:11 UTC, merged