Refactored terminal.py
GamestonkTerminal/GamestonkTerminal pull request #1312
Opened 2022-02-04 03:07 UTC by colin99d

# Description

We seem to like adding custom flags to terminal.py. This is getting increasingly complex. I simplified this by converting the main function into using argparse. Also, we are integrating the all_scripts command directly into the terminal. This will make our integration tests much easier from now on. Please note that just running -s results in all scripts being ran, while -s stocks results in all scripts with "stocks" in the file path being ran.

Things I still need to do before this is ready to push: 

- [ ] Don't break on scripts failure
- [ ] Introduce a way to keep track of which commands had an error

# How has this been tested?

I ran this through about every edge case I thought of. But @jmaslek is willing to write a thesis for anyone that can find an error.

# Checklist:

- [ ] Update [our Hugo documentation](https://gamestonkterminal.github.io/GamestonkTerminal/) following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

2022-02-04 03:40 UTC, jmaslek reviewed
Looks good to me.  I'll leave to the real devs to confirm :P

2022-02-04 03:40 UTC, jmaslek commented on terminal.py
> +                if file[-4:] == ".gst":
if file.endswith(".gst")

2022-02-04 14:15 UTC, DidierRLopes commented
If it has @jmaslek stamp on it, I'm fine with this!

2022-02-05 03:36 UTC, colin99d commented
@Chavithra and I are having an issue with capture output. Once we can resolve this we should be good to go.

2022-02-07 00:15 UTC, Chavithra commented
Do you it it would be interesting to automatically append `exit` to the queue after loading the script ?

2022-02-07 00:17 UTC, colin99d commented
> @colin99d Do you it it would be interesting to automatically append `exit` to the queue after loading the script ?

I think that would be very wise.

2022-02-08 19:59 UTC, DidierRLopes commented
Is this ready for review?

2022-02-08 22:22 UTC, DidierRLopes requested changes
Getting an error with `test_stocks_disc.gst`
<img width="425" alt="Screenshot 2022-02-08 at 22 15 46" src="https://user-images.githubusercontent.com/25267873/153084776-54cb86e1-4a7f-4899-89a2-383d1355844a.png">

If we have 2 errors on the same file, I think only one appears.
<img width="479" alt="Screenshot 2022-02-08 at 22 18 25" src="https://user-images.githubusercontent.com/25267873/153085107-094883cb-c3aa-4082-af93-ab4084d41dc7.png">

If possible would be great to have a:
14/14
11/12
9/9

i.e. success/failures per commands within a file.

In addition, I think that "test" could be a flag and we could filter as you have it.. 
And someone could do:
* `python terminal.py scripts/test.gst --test`
* `python terminal.py scripts/ --test`
* `python terminal.py scripts/ --test -f disc`

2022-02-08 22:22 UTC, DidierRLopes commented on gamestonk_terminal/portfolio/portfolio_view.py
> +        console.print(e)
If there's an error we don't want to show or export something.

In any case, I don't think we need this try-except block here

2022-02-08 22:25 UTC, colin99d commented
@DidierRLopes so you would like to see a test flag and a filter flag separate, instead of the combined method I have used ie. `python terminal.py -t stocks`?

2022-02-08 23:39 UTC, DidierRLopes commented
> @DidierRLopes so you would like to see a test flag and a filter flag separate, instead of the combined method I have used ie. `python terminal.py -t stocks`?

Kind of. But even a path to the folder being given instead of having a pre-defined

2022-02-10 00:19 UTC, DidierRLopes commented
Path should allowed to be a file, and since `-t` flag is enabled it should output success/fail
<img width="903" alt="Screenshot 2022-02-10 at 00 17 56" src="https://user-images.githubusercontent.com/25267873/153312739-982378be-5b14-428e-b471-0d90c8755d85.png">

Apart from this things are looking great 😄

2022-02-10 10:20 UTC, DidierRLopes approved these changes
Let's goooo!

2022-02-10 10:20 UTC, merged