This one WEIRD trick will reduce new bot code by 90%
GamestonkTerminal/GamestonkTerminal pull request #1480
Opened 2022-03-13 17:43 UTC by colin99d

# Description

@DidierRLopes still hasn't made an AOL bot so I decided to take away his excuses. Thanks to some genius from @jose-donato we have abstracted the interface for bots. This means new bots just need a function for sending messages and sending images. So easy!!!

What has been/needs done:
- [ ] Create a function to abstract new bot creation
- [ ] Refactor telegram bot
- [ ] Refactor groupme bot
- [ ] Refactor slash bot

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://gamestonkterminal.github.io/GamestonkTerminal/) following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

2022-03-13 17:58 UTC, jmaslek commented
So can I do AIM yet

2022-03-13 21:05 UTC, DidierRLopes commented
what have I done this time? :(

2022-03-15 01:34 UTC, colin99d commented
This code has known bugs, but @tehcoderer has a PR that fixes most of them. Will do a run through once both PRs are merged to see which commands still have issues.

2022-03-15 05:54 UTC, tehcoderer approved these changes
Great work with the helpers! Can't wait for some samsung fridge bots !

2022-03-15 05:54 UTC, tehcoderer commented on bots/common/helpers.py
> +                func = selected["function"]
```py
                if (isinstance(required, List) and val not in required) or (
                    isinstance(required, Pattern) and not required.match(val)
                ):
                    syntax = get_syntax(selected, full_cmd[0])
                    bot.reply_to(message, f"{syntax}\nInvalid argument for: {req_name}")
                    get_arguments(selected, req_name, message)
                    return False
                elif isinstance(val, str) and req_name == "interval":
                    val = int(val)
                elif isinstance(val, str) and req_name == "strike":
                    val = float(val)
                other_args[req_name] = val
            func = selected["function"]
 ```

In my tests adding this fixed the int/float type issues    🚀

2022-03-15 05:54 UTC, tehcoderer commented on bots/common/commands_dict.py
>          "required": {"ticker": tickers, "expiry": re_date},
I was able to get the expiry dates args to work only after I changed `re_date` to `re_name`. Issue with the re.Pattern?

2022-03-15 14:30 UTC, jose-donato requested changes
`bots/ta_kc.png` i assume this was also added by mistake

2022-03-15 14:30 UTC, jose-donato commented on bots/common/helpers.py
> +    message: Any
wrong sender docstring

2022-03-15 16:23 UTC, colin99d commented on bots/common/helpers.py
> +    if text[0] == "!":
Bet.

2022-03-15 16:33 UTC, DidierRLopes commented on bots/common/helpers.py
> +    if text[0] == "!":
> ```python
> ```python
> if text[0] == "!" or "/":
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Would this work? haha
> ```

In order to achieve this you would want to do:
`if text[0] in ("!", "/"):`

2022-03-16 00:01 UTC, jose-donato approved these changes

2022-03-16 01:29 UTC, merged