Add YahooFinance to forex load
GamestonkTerminal/GamestonkTerminal pull request #1544
Opened 2022-03-24 05:34 UTC by minhhoang1023

# Description

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://gamestonkterminal.github.io/GamestonkTerminal/) following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

2022-03-24 08:09 UTC, piiq requested changes
Nice!

The only thing that I propose changing is Oanda.

Oanda is a trading platform and a data source by itself.
As a data source it has a lot less pairs available than `ya` and `av`. If we enter the menu with a random pair Oanda will likely not have that pair supported. I wouldn't pass the `to` and `from` symbols and the `source` to Oanda but rather "lock" the menu if the API key is not set.

2022-03-24 08:09 UTC, piiq commented on gamestonk_terminal/forex/forex_controller.py
> +            "--source",
let's add an `-s` flag too?

2022-03-25 00:51 UTC, jmaslek commented
Looks nice.  I have two comments

1) The `load` function has 2 -s options.  So we get

```
2022 Mar 24, 20:46 (✨) /forex/ $ load -h
Error: argument -s/--start_date: conflicting option string: -s
```

2) Very small, but on the main forex menu, can the spacings be just one line instead of 2.  Example:

```
│ Source: YahooFinance                                                                                                                                                                
│                                                                                                                                                                                     
│     (remove one of these spaces)                                                                                                                                                                                │
│     quote         get last quote [AlphaVantage]                                                                                                                                     
│     load          get historical data                                                                                                                                               
│     candle        show candle plot for loaded data   
```

Same between ta and brokerages

2022-03-25 13:11 UTC, piiq approved these changes

2022-03-25 13:11 UTC, merged