Allow to load data from IEX
GamestonkTerminal/GamestonkTerminal pull request #536
Opened 2021-07-09 11:41 UTC by DidierRLopes

I went over the credits of IEX. I don't think it has a great free tier.

But anyway, it has a lot of stuff that we can perhaps integrate at some point. So probably worth having this as a starting point.

See https://github.com/iexcloud/pyEX/blob/main/examples/all.ipynb

2021-07-09 14:27 UTC, jmaslek approved these changes

2021-07-09 14:27 UTC, jmaslek commented on gamestonk_terminal/main_helper.py
> +                print(df_stock_candidate.to_string())
Do you want this to print?

2021-07-09 14:30 UTC, jmaslek reviewed
Also intraday doesn't work  (note `load msft --source iex` works)

![Screen Shot 2021-07-09 at 10 28 59 AM](https://user-images.githubusercontent.com/18151143/125093742-9c80ad80-e0a0-11eb-829f-9f531896d46b.png)

2021-07-09 14:41 UTC, jmaslek requested changes
So the intraday option is not available for iex as written.  Not sure if you want to have a flag that says that or add it in (I think the `client.chart` has some extra kwargs for intraday (https://github.com/iexcloud/pyEX/blob/d9c38826ebc5c35ffb80903f006834a5989d70c5/pyEX/stocks/prices.py#L87))

2021-07-11 10:50 UTC, DidierRLopes commented on gamestonk_terminal/main_helper.py
> +                print(df_stock_candidate.to_string())
Nahhh

2021-07-11 10:50 UTC, DidierRLopes commented
> So the intraday option is not available for iex as written. Not sure if you want to have a flag that says that or add it in (I think the `client.chart` has some extra kwargs for intraday (https://github.com/iexcloud/pyEX/blob/d9c38826ebc5c35ffb80903f006834a5989d70c5/pyEX/stocks/prices.py#L87))

Yea, the intraday only gives 1m for the day... I'm gonna try to play with that

2021-07-11 12:18 UTC, DidierRLopes commented
@jmaslek I've added a couple of things to this PR :) Should be in a good shape now

2021-07-11 18:05 UTC, jmaslek commented on gamestonk_terminal/main_helper.py
> +                print(df_stock_candidate.to_string())
Still does

2021-07-11 18:07 UTC, jmaslek commented
After I do `load AAPL -i 1 --source iex` , the `view` is weird

2021-07-11 18:59 UTC, jmaslek approved these changes

2021-07-12 07:17 UTC, aia approved these changes

2021-07-12 19:46 UTC, merged